name: pyearthviz-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - scipy
  - gdal
  - matplotlib
  - cartopy
  - statsmodels
  - pyearth>=0.2.2
  - pip
  - pip:
    - -e .
